### ISSUE TITLE
Pbl in W1KG13126

### ISSUE THREAD

**Issue by brunogml** [Esukhia/tengyur-pagination#1]
From W1KG13126-10 you list the work W23702

**Comment by eroux** [comment]
The csv I created were committed in the first commit ([here](https://github.com/Esukhia/tengyur-pagination/tree/7088dd8e67be0fbb055b41b424a2a74e26afc3d3/Tengyur%20image%20csv/csv)) and they seem ok, there must have been some problem later in the pipeline

**Comment by ngawangtrinley** [comment]
We're working on the 3 csv that got mixed up. Should be done tomorrow

**Comment by eroux** [comment]
they've been updated!
